server:
  port: 8084   # ✅ choose next available port after card-service (8083)

spring:
  application:
    name: loanservice   # consistent with our no-hyphen naming style
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: bank
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

  jackson:
    serialization:
      INDENT_OUTPUT: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/banking-app


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000




services:
  users:
    url: http://localhost:8081
  accounts:
    url: http://localhost:8082
  cards:
    url: http://localhost:8083












